### ISSUE TITLE
Documenting project decisions

### ISSUE THREAD

**Issue by yasharpm** [pondersource/CYB#29]
I think in a meeting with @michielbdejong we agreed to record the project decisions in a documents folder next to project files. I feel proud to have put the laravel project in a subfolder when I pushed the initial code!

I think a "doc" or "documents" folder on the root of the repository makes a good fit. And we will need to move the Structure.md and other relevant files into that folder as well.

Then whenever we make a conclusion about a decision like [Issue 28](https://github.com/pondersource/CYB/issues/28), we can include it in that document.

I have no idea for the format to write them down. Like many files or one file or maybe a folder structure. Personally, I think we can start with whatever and then see how we can organize them after we have a bunch of them there.

Also, seems like a good idea that the person who created the issue (or closes it?) will make sure it is documented.

What do you think?

**Comment by mlesmenio** [comment]
This makes sense. I would start with 1 doc folder and 1 file in it and hope that at some point it will make sense to split it into more files. I would say to check if the issue is documented upon closing so that it has a comment like "closed because of [link]".

**Comment by yasharpm** [comment]
I guess it's decided then!
