### ISSUE TITLE
Questions about the new design document

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/CYB#33]
Referring to @mlesmenio's [new design document](https://github.com/pondersource/CYB/blob/main/Design%20Information/README.md) here are some questions I had while reading:

> The goal in this project is to automate the sync[h]ronization of data across different apps where the formats aren't identical.
[...]
> Update Notifier - Checks the available resources of the application being synced to set up a notification system that will make requests either when a new entry is made (if webhooks are available) or periodically.

The first sentence makes sense to me - there are multiple apps and CYB sits in the middle.
But it wasn't clear to me what "the" application is in the second sentence. The text seems to say that CYB has 5 parts, and one of those parts is called "update notifier". But how many update notifiers are there? One for all of CYB or one per app?

**Comment by mlesmenio** [comment]
I meant to say it was one update notifier for each app being synched are it
check the resources for each one.
I updated it in the meantime, it should be more clear now

Michiel de Jong ***@***.***> escreveu no dia terça,
17/01/2023 à(s) 08:03:

**Comment by michielbdejong** [comment]
Great!
